version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - database

  frontend-web:
    build: ../frontend-web
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend-mobile:
    build: ../frontend-mobile
    ports:
      - "19000:19000"
      - "19001:19001"
    depends_on:
      - backend

  frontend-desktop:
    build: ../frontend-desktop
    ports:
      - "4000:4000"
    depends_on:
      - backend

  database:
    image: ${DATABASE_IMAGE:-postgres:latest}
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
